name: Build, Test, and Run
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./workflows/ci/fetchCFE.sh
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "yelllo"
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "yelller"
