name: Build, Test, and Run
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions/build-action
        with:
          NAME: "Build ECI"
