name: Build and Test
on: 
  push
  pull_request
jobs:
  build:
    name: Build and Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
	with:
	  MY_NAME: "Oliver"
