name: Build, Test, and Run
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get update
      - run: sudo apt-get install gcc-multilib

      - name: Build
      - run: ./.github/workflows/ci/fetchCFE.sh
      - run: ./.github/workflows/ci/buildSimpleExample.sh
      - run: ./.github/workflows/ci/fetchCFE.sh
      - run: ./.github/workflows/ci/buildSGP4Example.sh
      
      - name: Test
      - run: ./.github/workflows/ci/runECIUnitTest.sh
      - run: ./.github/workflows/ci/runSGP4UnitTest.sh

      
